"""
Seed 20 Bonobos-style fashion products + 5 outfit guides for RAG demo.
Run: python scripts/seed_sample_data.py
"""
import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.config import get_settings
from app.ingestion.product_loader import index_outfit, index_product
from app.models.product import FashionCategory, FashionProduct, FitType

settings = get_settings()

SAMPLE_PRODUCTS = [
    {
        "sku": "BNB-CHINO-SLIM-KHK",
        "name": "Weekday Warrior Slim Chino",
        "category": FashionCategory.CHINOS,
        "description": "Bonobos' signature chino with 4-way stretch fabric and a slim cut that's ideal for work or weekend.",
        "style_notes": "The perfect bridge between business casual and weekend wear. Clean lines and a tailored silhouette.",
        "how_to_wear": "Pair with a white OCBD shirt and loafers for business casual, or a polo and white sneakers for weekend.",
        "pairs_well_with": "Classic Oxford shirts, polo shirts, loafers, white leather sneakers",
        "fit_type": FitType.SLIM,
        "color": "Khaki",
        "color_family": "neutral",
        "pattern": "solid",
        "material": "97% cotton, 3% elastane",
        "occasion": ["business_casual", "smart_casual", "weekend"],
        "season": ["spring", "summer", "fall"],
        "waist_sizes": ["28", "29", "30", "31", "32", "33", "34", "35", "36", "38", "40"],
        "inseam_sizes": ["28", "30", "32", "34"],
        "price_usd": 98.0,
        "rating": 4.7,
        "review_count": 3421,
    },
    {
        "sku": "BNB-CHINO-ATH-NVY",
        "name": "Weekday Warrior Athletic Fit Chino — Navy",
        "category": FashionCategory.CHINOS,
        "description": "Athletic fit with extra room through the seat and thighs. Built for guys who work out but still need to work.",
        "style_notes": "The answer for athletic builds who struggle with traditional slim cuts.",
        "how_to_wear": "Navy chinos are incredibly versatile — wear to office or out to dinner.",
        "pairs_well_with": "Chambray shirts, blazers, classic leather dress shoes",
        "fit_type": FitType.ATHLETIC,
        "color": "Navy",
        "color_family": "navy",
        "pattern": "solid",
        "material": "97% cotton, 3% elastane",
        "occasion": ["business_casual", "smart_casual", "date_night"],
        "season": ["fall", "winter", "spring"],
        "waist_sizes": ["30", "32", "33", "34", "35", "36", "38", "40"],
        "inseam_sizes": ["28", "30", "32", "34"],
        "price_usd": 98.0,
        "rating": 4.8,
        "review_count": 2134,
    },
    {
        "sku": "BNB-SUIT-SLIM-CHAR",
        "name": "Italian Stretch Suit Jacket — Slim — Charcoal",
        "category": FashionCategory.SUITS,
        "description": "A modern slim-fit suit crafted from Italian stretch wool blend. Structured shoulders with a natural chest.",
        "style_notes": "Clean, contemporary suit that doesn't look rented. The stretch wool allows full range of motion.",
        "how_to_wear": "As a 2-piece suit with the matching trousers, or break apart as a blazer with dark denim.",
        "pairs_well_with": "White dress shirt, silk tie, Oxford shoes, pocket square",
        "fit_type": FitType.SLIM,
        "color": "Charcoal",
        "color_family": "neutral",
        "pattern": "solid",
        "material": "95% wool, 5% elastane (Italian mill)",
        "occasion": ["business_formal", "wedding", "date_night"],
        "season": ["fall", "winter"],
        "price_usd": 498.0,
        "rating": 4.8,
        "review_count": 876,
    },
    {
        "sku": "BNB-POLO-SLIM-WHT",
        "name": "The Riviera Polo — Slim — White",
        "category": FashionCategory.POLOS,
        "description": "Performance polo with moisture-wicking fabric and UPF 50+ sun protection. A wardrobe essential.",
        "style_notes": "Versatile in the best way — wear to golf, the office, or weekend brunch.",
        "how_to_wear": "Tuck into chinos for smart casual, or wear untucked with shorts for weekend looks.",
        "pairs_well_with": "Khaki chinos, navy shorts, white sneakers, loafers",
        "fit_type": FitType.SLIM,
        "color": "White",
        "color_family": "neutral",
        "pattern": "solid",
        "material": "100% performance pique cotton",
        "occasion": ["business_casual", "smart_casual", "weekend", "outdoor"],
        "season": ["spring", "summer"],
        "shirt_sizes": ["XS", "S", "M", "L", "XL", "XXL"],
        "price_usd": 68.0,
        "rating": 4.6,
        "review_count": 1543,
    },
    {
        "sku": "BNB-OXFRD-SLIM-LBL",
        "name": "The Oxford Shirt — Slim — Light Blue",
        "category": FashionCategory.SHIRTS,
        "description": "Classic light blue OCBD Oxford shirt — the cornerstone of any smart casual wardrobe.",
        "style_notes": "The light blue OCBD is arguably the most versatile shirt a man can own.",
        "how_to_wear": "With navy chinos and loafers for business casual. Untucked with jeans for weekend.",
        "pairs_well_with": "Navy or khaki chinos, dark denim, loafers or white sneakers",
        "fit_type": FitType.SLIM,
        "color": "Light Blue",
        "color_family": "navy",
        "pattern": "solid",
        "material": "100% combed cotton Oxford weave",
        "occasion": ["business_casual", "smart_casual", "weekend"],
        "season": ["spring", "summer", "fall"],
        "shirt_sizes": ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
        "price_usd": 88.0,
        "rating": 4.7,
        "review_count": 4321,
    },
    {
        "sku": "BNB-DENIM-ATH-IND",
        "name": "5-Pocket Athletic Stretch Jean — Indigo",
        "category": FashionCategory.JEANS,
        "description": "Jeans with the comfort of sweatpants and the look of denim. 4-way stretch for athletic builds.",
        "style_notes": "Built for guys who've given up on denim because regular cuts don't fit. This changes that.",
        "how_to_wear": "Dress up with a blazer and loafers, or keep it casual with a tee and sneakers.",
        "pairs_well_with": "Polo shirts, casual button-downs, blazers, chelsea boots",
        "fit_type": FitType.ATHLETIC,
        "color": "Indigo",
        "color_family": "navy",
        "pattern": "solid",
        "material": "87% cotton, 11% polyester, 2% elastane",
        "occasion": ["smart_casual", "casual", "weekend", "date_night"],
        "season": ["fall", "winter"],
        "waist_sizes": ["28", "30", "32", "33", "34", "35", "36", "38"],
        "inseam_sizes": ["28", "30", "32", "34"],
        "price_usd": 128.0,
        "rating": 4.8,
        "review_count": 3241,
    },
    {
        "sku": "BNB-BLZR-NAV-SLIM",
        "name": "Italian Stretch Blazer — Slim — Navy",
        "category": FashionCategory.BLAZERS,
        "description": "Unstructured Italian-stretch blazer that moves with you. Notch lapel, double back vent.",
        "style_notes": "The essential blazer for men who hate how blazers feel.",
        "how_to_wear": "Over a white tee and chinos for smart casual. With dress trousers for business.",
        "pairs_well_with": "Light blue OCBD, white tee, chinos, dark jeans",
        "fit_type": FitType.SLIM,
        "color": "Navy",
        "color_family": "navy",
        "pattern": "solid",
        "material": "Stretch wool blend",
        "occasion": ["business_casual", "smart_casual", "date_night", "wedding"],
        "season": ["fall", "winter", "spring"],
        "shirt_sizes": ["XS", "S", "M", "L", "XL", "XXL"],
        "price_usd": 248.0,
        "rating": 4.7,
        "review_count": 2134,
    },
    {
        "sku": "BNB-SWIM-STR-TROPIC",
        "name": "5.5\" Solid Swim Trunks — Tropical Green",
        "category": FashionCategory.SWIMWEAR,
        "description": "Quick-dry swim trunks with a shorter 5.5-inch inseam and built-in mesh liner.",
        "style_notes": "The length sweet spot — short enough to look intentional, long enough to be appropriate anywhere.",
        "how_to_wear": "From pool to street with a linen shirt unbuttoned over a tee.",
        "pairs_well_with": "Linen shirts, polo shirts, sandals, loafers",
        "fit_type": FitType.SLIM,
        "color": "Tropical Green",
        "color_family": "earth",
        "pattern": "solid",
        "material": "100% recycled polyester",
        "occasion": ["casual", "weekend", "outdoor"],
        "season": ["summer"],
        "waist_sizes": ["28", "29", "30", "31", "32", "33", "34", "36", "38"],
        "price_usd": 78.0,
        "rating": 4.6,
        "review_count": 987,
    },
    {
        "sku": "BNB-SHORT-9-OLIVE",
        "name": "Weekend 9-Inch Short — Olive",
        "category": FashionCategory.SHORTS,
        "description": "9-inch inseam stretch shorts with a 4-way stretch. The ideal summer weekend short.",
        "style_notes": "The perfect length for men who want to look put-together without trying too hard.",
        "how_to_wear": "With a polo or casual button-down. Works for summer golf too.",
        "fit_type": FitType.ATHLETIC,
        "color": "Olive",
        "color_family": "earth",
        "pattern": "solid",
        "material": "92% nylon, 8% elastane",
        "occasion": ["casual", "weekend", "outdoor"],
        "season": ["summer"],
        "waist_sizes": ["28", "30", "32", "33", "34", "36", "38"],
        "price_usd": 78.0,
        "rating": 4.5,
        "review_count": 1234,
    },
    {
        "sku": "BNB-CREW-MERINO-GRY",
        "name": "Merino Wool Crew Neck Sweater — Grey",
        "category": FashionCategory.SWEATERS,
        "description": "Lightweight merino wool crew neck — the versatile layering piece for fall and winter.",
        "style_notes": "Fine-gauge merino that works under a blazer or on its own.",
        "how_to_wear": "Layer over an OCBD for a European-inspired look. Great for smart casual office attire.",
        "pairs_well_with": "Oxford shirts, chinos, dark denim, Chelsea boots",
        "fit_type": FitType.SLIM,
        "color": "Grey",
        "color_family": "neutral",
        "pattern": "solid",
        "material": "100% Merino wool",
        "occasion": ["business_casual", "smart_casual", "weekend"],
        "season": ["fall", "winter"],
        "shirt_sizes": ["XS", "S", "M", "L", "XL", "XXL"],
        "price_usd": 118.0,
        "rating": 4.7,
        "review_count": 1876,
    },
    {
        "sku": "BNB-PARKA-NVY",
        "name": "The Glacier Park Parka — Navy",
        "category": FashionCategory.OUTERWEAR,
        "description": "Water-resistant insulated parka with 650-fill down and a removable hood.",
        "style_notes": "The parka that looks like you put thought into it without sacrificing warmth.",
        "how_to_wear": "Over a sweater or hoodie for weekend. Over a blazer for a smart winter look.",
        "fit_type": FitType.TAILORED,
        "color": "Navy",
        "color_family": "navy",
        "pattern": "solid",
        "material": "Shell: 100% nylon. Fill: 650-fill down",
        "occasion": ["casual", "weekend", "smart_casual"],
        "season": ["winter", "fall"],
        "shirt_sizes": ["XS", "S", "M", "L", "XL", "XXL"],
        "price_usd": 298.0,
        "rating": 4.6,
        "review_count": 876,
    },
    {
        "sku": "BNB-BELT-BRN-LTH",
        "name": "Full-Grain Leather Belt — Brown",
        "category": FashionCategory.ACCESSORIES,
        "description": "Full-grain leather belt with an antique brass buckle. Gets better with age.",
        "style_notes": "The detail that finishes any business casual or smart casual look.",
        "pairs_well_with": "Chinos, dress trousers, suits, loafers or Oxford shoes",
        "color": "Brown",
        "color_family": "earth",
        "material": "Full-grain leather",
        "occasion": ["business_casual", "business_formal", "smart_casual"],
        "price_usd": 68.0,
        "rating": 4.7,
        "review_count": 2341,
    },
    {
        "sku": "BNB-STRIPE-WOVEN",
        "name": "Seersucker Stripe Woven Shirt — Blue/White",
        "category": FashionCategory.SHIRTS,
        "description": "Classic seersucker stripe shirt with a textured weave that looks crisp and keeps you cool.",
        "style_notes": "Summer's answer to the white dress shirt. Instantly more interesting but equally versatile.",
        "how_to_wear": "Tucked into white chinos for smart casual. Untucked at a garden party.",
        "pairs_well_with": "White or khaki chinos, loafers, boat shoes",
        "fit_type": FitType.SLIM,
        "color": "Blue/White",
        "color_family": "navy",
        "pattern": "stripe",
        "material": "100% cotton seersucker",
        "occasion": ["smart_casual", "casual", "weekend", "wedding"],
        "season": ["spring", "summer"],
        "shirt_sizes": ["XS", "S", "M", "L", "XL", "XXL"],
        "price_usd": 88.0,
        "rating": 4.5,
        "review_count": 654,
    },
    {
        "sku": "BNB-CHINO-STRAIGHT-OLV",
        "name": "Weekday Warrior Straight Chino — Olive",
        "category": FashionCategory.CHINOS,
        "description": "A straighter, more relaxed cut for those who prefer a classic chino silhouette.",
        "style_notes": "Relaxed without being baggy. A modern take on the classic straight-leg chino.",
        "fit_type": FitType.STRAIGHT,
        "color": "Olive",
        "color_family": "earth",
        "pattern": "solid",
        "material": "97% cotton, 3% elastane",
        "occasion": ["casual", "weekend", "smart_casual"],
        "season": ["fall", "spring"],
        "waist_sizes": ["30", "32", "33", "34", "36", "38", "40"],
        "inseam_sizes": ["28", "30", "32", "34"],
        "price_usd": 98.0,
        "rating": 4.6,
        "review_count": 1234,
    },
    {
        "sku": "BNB-TUXEDO-SLIM",
        "name": "The Tuxedo Suit — Slim — Black",
        "category": FashionCategory.SUITS,
        "description": "Modern slim tuxedo with grosgrain lapels and a non-vented single-button jacket.",
        "style_notes": "A tuxedo that fits — the rarest thing in menswear.",
        "how_to_wear": "With a white tuxedo shirt, black bow tie, and patent leather shoes.",
        "pairs_well_with": "White tuxedo shirt, black bow tie, cummerbund, patent leather Oxfords",
        "fit_type": FitType.SLIM,
        "color": "Black",
        "color_family": "neutral",
        "pattern": "solid",
        "material": "100% wool",
        "occasion": ["wedding", "business_formal"],
        "season": ["fall", "winter"],
        "price_usd": 598.0,
        "rating": 4.9,
        "review_count": 432,
    },
    {
        "sku": "BNB-LINEN-SHIRT-WHT",
        "name": "The Linen Shirt — Slim — White",
        "category": FashionCategory.SHIRTS,
        "description": "Lightweight linen shirt perfect for hot weather. Breathable, slightly textured, effortlessly cool.",
        "style_notes": "White linen = summer sophistication. Wear it half-tucked for a relaxed Italian feel.",
        "how_to_wear": "With linen or chino shorts for casual. Tucked into khaki chinos for smart casual.",
        "fit_type": FitType.SLIM,
        "color": "White",
        "color_family": "neutral",
        "pattern": "solid",
        "material": "100% linen",
        "occasion": ["casual", "weekend", "smart_casual"],
        "season": ["summer"],
        "shirt_sizes": ["XS", "S", "M", "L", "XL", "XXL"],
        "price_usd": 88.0,
        "rating": 4.6,
        "review_count": 876,
    },
    {
        "sku": "BNB-CHINO-TAILORED-GRY",
        "name": "The Dress Chino — Tailored — Grey",
        "category": FashionCategory.PANTS,
        "description": "Elevated chino with a tailored cut and a slightly higher rise for a more formal look.",
        "style_notes": "The gap between chino and dress trouser. Blurs the line in the best possible way.",
        "how_to_wear": "With a dress shirt or blazer for business. With a sweater for smart casual.",
        "fit_type": FitType.TAILORED,
        "color": "Grey",
        "color_family": "neutral",
        "pattern": "solid",
        "material": "70% wool, 25% polyester, 5% elastane",
        "occasion": ["business_formal", "business_casual", "smart_casual"],
        "season": ["fall", "winter"],
        "waist_sizes": ["28", "30", "32", "33", "34", "36"],
        "inseam_sizes": ["28", "30", "32", "34"],
        "price_usd": 128.0,
        "rating": 4.7,
        "review_count": 987,
    },
    {
        "sku": "BNB-QUARTER-ZIP",
        "name": "Performance Quarter-Zip Pullover — Black",
        "category": FashionCategory.SWEATERS,
        "description": "Moisture-wicking quarter-zip with a soft fleece interior and a sporty, slim silhouette.",
        "style_notes": "The professional-looking alternative to a hoodie.",
        "how_to_wear": "Layer over a polo or under a jacket. Works for office or weekend.",
        "fit_type": FitType.SLIM,
        "color": "Black",
        "color_family": "neutral",
        "pattern": "solid",
        "material": "100% polyester micro-fleece",
        "occasion": ["business_casual", "casual", "outdoor"],
        "season": ["fall", "winter"],
        "shirt_sizes": ["XS", "S", "M", "L", "XL", "XXL"],
        "price_usd": 88.0,
        "rating": 4.5,
        "review_count": 1234,
    },
    {
        "sku": "BNB-FLANNEL-PLAID",
        "name": "Flannel Shirt — Slim — Autumn Plaid",
        "category": FashionCategory.SHIRTS,
        "description": "Soft brushed flannel shirt in a classic autumn plaid. Perfect weight for fall layering.",
        "style_notes": "Plaid done right — the pattern is large enough to make a statement, muted enough for the office.",
        "how_to_wear": "Open over a white tee and jeans for casual. Buttoned with chinos for smart casual.",
        "fit_type": FitType.SLIM,
        "color": "Burgundy/Green/Tan",
        "color_family": "earth",
        "pattern": "plaid",
        "material": "100% cotton brushed flannel",
        "occasion": ["casual", "weekend", "smart_casual"],
        "season": ["fall"],
        "shirt_sizes": ["XS", "S", "M", "L", "XL", "XXL"],
        "price_usd": 98.0,
        "rating": 4.7,
        "review_count": 1543,
    },
    {
        "sku": "BNB-VELVET-BLZR",
        "name": "Velvet Blazer — Slim — Forest Green",
        "category": FashionCategory.BLAZERS,
        "description": "Rich forest green velvet blazer for special occasions. Unlined for comfort, peak lapel for drama.",
        "style_notes": "For when you want to be remembered. Pairs surprisingly well with simple basics.",
        "how_to_wear": "With a white tee and black chinos for a fashion-forward look. Or over a black turtleneck.",
        "pairs_well_with": "White tee, black chinos, black turtleneck, Chelsea boots",
        "fit_type": FitType.SLIM,
        "color": "Forest Green",
        "color_family": "earth",
        "pattern": "solid",
        "material": "65% cotton, 35% viscose velvet",
        "occasion": ["date_night", "wedding", "smart_casual"],
        "season": ["fall", "winter"],
        "shirt_sizes": ["XS", "S", "M", "L", "XL"],
        "price_usd": 278.0,
        "rating": 4.8,
        "review_count": 543,
    },
]

SAMPLE_OUTFITS = [
    {
        "title": "The Modern Business Casual",
        "occasion": "business_casual",
        "season": "fall",
        "description": "The go-to office look for environments that mean business but not a suit.",
        "items": "Weekday Warrior Athletic Chino in Navy + Light Blue Oxford Shirt (slim, tucked) + Italian Stretch Blazer (navy) + Leather Belt (brown) + Loafers or Oxford shoes. Optional: Merino wool crew neck instead of blazer on casual Fridays.",
    },
    {
        "title": "Weekend Smart Casual",
        "occasion": "smart_casual",
        "season": "spring",
        "description": "Effortlessly put-together for brunch, shopping, or casual dates.",
        "items": "Weekday Warrior Slim Chino in Khaki + The Riviera Polo (white or navy) + White leather sneakers. Alternative: swap polo for a linen shirt half-tucked for warmer weather.",
    },
    {
        "title": "Summer Wedding Guest",
        "occasion": "wedding",
        "season": "summer",
        "description": "Appropriate for an outdoor summer wedding — festive but polished.",
        "items": "Italian Stretch Suit in Charcoal + White Dress Shirt + Pocket square + Oxford shoes. Alternatively for a garden wedding: Seersucker Stripe Shirt + White Chinos + Loafers — skip the jacket.",
    },
    {
        "title": "Date Night — Smart Elevated",
        "occasion": "date_night",
        "season": "fall",
        "description": "You want to look like you put in effort without looking like you tried too hard.",
        "items": "Italian Stretch Blazer (navy) + White Oxford Shirt (untucked) + Athletic Stretch Jeans (indigo) + Chelsea boots. The blazer over jeans is the perfect formula — polished top, relaxed bottom.",
    },
    {
        "title": "Cold Weather Weekend",
        "occasion": "casual",
        "season": "winter",
        "description": "Comfortable, practical, and still looks intentional.",
        "items": "Glacier Park Parka (navy) + Merino Crew Neck Sweater (grey) + 5-Pocket Athletic Stretch Jean + Chelsea boots or white sneakers. Add a scarf for extra warmth and a finishing touch.",
    },
]


async def seed() -> None:
    engine = create_async_engine(settings.database_url, echo=False)
    SessionLocal = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with SessionLocal() as session:
        for data in SAMPLE_PRODUCTS:
            result = await session.execute(
                select(FashionProduct).where(FashionProduct.sku == data["sku"])
            )
            if result.scalar_one_or_none():
                print(f"  Exists: {data['name']}")
                continue
            product = FashionProduct(**data)
            session.add(product)
            print(f"  Added: {data['name']}")

        await session.commit()

    # Index into ChromaDB
    for data in SAMPLE_PRODUCTS:
        product_dict = dict(data)
        ids = index_product(product_dict)
        print(f"  Indexed in Chroma: {data['name']} ({len(ids)} chunks)")

    for outfit in SAMPLE_OUTFITS:
        ids = index_outfit(outfit)
        print(f"  Indexed outfit: {outfit['title']} ({len(ids)} chunks)")

    print(f"\nSeeded {len(SAMPLE_PRODUCTS)} fashion products and {len(SAMPLE_OUTFITS)} outfits.")
    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(seed())
